INSERT INTO AA_CRIT_PPHYS
(NO_REL_CLT, NOM_USAGE, PRENOM)
VALUES ('11046189', 'Girodon', 'Remy');

INSERT INTO AA_CRIT_PPHYS
(NO_REL_CLT, NOM_USAGE, PRENOM)
VALUES ('11046188', 'Dupont', 'Michel');

INSERT INTO AA_CRIT_PPHYS
(NO_REL_CLT, NOM_USAGE, PRENOM)
VALUES ('11046187', 'Durand', 'Arthur');